[package]
name = "complox"
version = "0.1.0"
edition = "2021"
description = "Lox but compiled to x86_64 assembly."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "lox"
path = "src/main.rs"
[dependencies]
